### ISSUE TITLE
Incompatible with Magic Actions for YouTube Extension

### ISSUE THREAD

**Issue by Jamilus** [simon--poole/ev-browser-extension-chrome#1]
The extension is currently unable to work when this one is enabled. Not sure if it's something that can be remedied on your end, but I thought I'd point it out anyway. [https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif](url)

**Comment by simon--poole** [comment]
Hi @Jamilus,

I'm running both side by side with no issues.
Could you go into more detail? In terms of what exactly works / doesn't work feature wise.
