### ISSUE TITLE
extension stopped working

### ISSUE THREAD

**Issue by MichaelRyanWebber** [simon--poole/ev-browser-extension-chrome#5]
I've disabled all other extensions, reinstalled this extension, and updated chrome. 

I feel like this is related to some chrome setting that I may have changed, but I can't find it. 

Any thoughts on what I should look for? By not work I mean, it doesn't hide anything, and this is the loleventvods youtube channel. 

I'm not great with js but I use the chrome console a lot. Happy to help in whatever way I can.

**Comment by simon--poole** [comment]
Related to the Youtube layout updates.
Will be fixed, but I'm pretty busy at the moment so no ETA yet I'm afraid!

**Comment by MichaelRyanWebber** [comment]
if you want to give me a hint, I can try to fix it. Understand about the
busy, thanks for the great work!

**Comment by simon--poole** [comment]
I haven't looked into the Youtube changes at all yet really, but it should just be a case of updating the DOM selectors. If you're familiar with HTML / Inspect Element chances are it won't be too hard, although Youtube's HTML is....painful at times.

**Comment by mcmar** [comment]
I'll try my hand at making some changes and see how far I can get.

@MichaelRyanWebber In the meantime, you can select "restore old Youtube" from the dropdown in the top-right (click on your picture or the three dots)

**Comment by MichaelRyanWebber** [comment]
thanks lovely people. Thanks for the hint Simon that makes sense to me.

**Comment by simon--poole** [comment]
Sorry for the late updates guys, I've just pushed a couple commits that should re-enable most of the base functionality.

Going to do some re-factoring and general testing before I push it to the Chrome store (so it'll be a couple days) but until then you can download the zip file + import it to Chrome as an unpacked extension if you want.
